server:
  port: 8080

spring:

  application:
    name: api-gateway

  config:
    import:
      optional:configserver:

  cloud:
    gateway:
      routes:
        - id: keycloak-token
          uri: http://localhost:8181
          predicates:
            - Path=/api/auth/login
          filters:
            - RewritePath=/api/auth/login, /realms/dating-app-realm/protocol/openid-connect/token

        - id: user-service
          uri: http://localhost:8090
          predicates:
              - Path=/api/users/**
          filters:
              - StripPrefix=2 # удаляет "/api/users", оставляя "/profiles/..."

keycloak:
  server-url: http://localhost:8181
  realm: dating-app-realm
  client-id: api-gateway
  client-secret: CM4MRn9HwHnFrvpOduJ3YapSIOxHlUUm
  admin-username: admin
  admin-password: admin


#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://${cloud.eureka-service-url}/eureka