server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import:
      optional:configserver:
  cloud:
    gateway:
      routes:
        - id: keycloak-token
          uri: http://localhost:8181
          predicates:
            - Path=/api/auth/login
          filters:
            - RewritePath=/api/auth/login, /realms/dating-app-realm/protocol/openid-connect/token


        - id: auth-service
          uri: http://localhost:9000
          predicates:
            - Path=/api/auth/register
          filters:
            - StripPrefix=1



        - id: user-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # адрес Eureka Server
  instance:
    prefer-ip-address: true  # регистрировать IP вместо hostname