server:
  port: 8090

cloud:
  db-host: localhost

spring:

  application:
    name: user-service

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.spatial.dialect.postgis.PostgreSQLPostgisDialect
  datasource:
    url: jdbc:postgresql://${cloud.db-host}:5434/usersDB
    username: user
    password: password
    driverClassName: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/dating-app-realm

  flyway:
    enabled: true
    locations: classpath:db
    url: jdbc:postgresql://${cloud.db-host}:5434/usersDB
    user: user
    password: password
